apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sgi-keycloak.fullname" . }}
  labels:
    {{- include "sgi-keycloak.labels" . | nindent 4 }}
  {{- if .Values.annotations.enabled }}
  {{- with .Values.annotations.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sgi-keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.annotations.enabled }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.annotations.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "sgi-keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sgi-keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ required "An image.repository value must be specified" .Values.image.repository }}:{{ required "Either image.tag or global.image.tag must be specified" (default .Values.global.image.tag .Values.image.tag) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy | default "IfNotPresent" }}
          args:
          {{- if eq (.Values.settings.importMode | default "if-absent") "if-absent" }}
          - start
          - --import-realm
          {{- else }}
          - start
          {{- end }}
          env:
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            {{- if kindIs "map" .Values.settings.keycloakUser }}
            {{- toYaml .Values.settings.keycloakUser | nindent 12 }}
            {{- else }}
            value: {{ .Values.settings.keycloakUser }}
            {{- end }}
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            {{- if kindIs "map" .Values.settings.keycloakPassword }}
            {{- toYaml .Values.settings.keycloakPassword | nindent 12 }}
            {{- else }}
            value: {{ .Values.settings.keycloakPassword }}
            {{- end }}
          - name: KC_PROXY_HEADERS
            value: {{ .Values.settings.proxyHeaders | default "xforwarded" | quote }}
          - name: KC_HTTP_ENABLED
            value: {{ .Values.settings.httpEnabled | default true | quote }}
          {{- with .Values.settings.hostname }}
          - name: KC_HOSTNAME
            value: {{ . | quote }}
          {{- else }}
          - name: KC_HOSTNAME_STRICT
            value: "false"
          {{- end }}
          {{- if .Values.extraEnvVariables }}
            {{- toYaml .Values.extraEnvVariables | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 9000
              protocol: TCP
          {{- if .Values.realmConfigMap.enabled }}
          volumeMounts:
          - name: realm-config
            mountPath: /opt/keycloak/data/import
            readOnly: true
          {{- end }}
          startupProbe:
            httpGet:
              path: /health/started
              port: management
            periodSeconds: 10
            failureThreshold: 90
          livenessProbe:
            httpGet:
              path: /health/live
              port: management
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.realmConfigMap.enabled }}
      volumes:
      - name: realm-config
        configMap:
          name: {{ .Values.realmConfigMap.name }}
          items:
          - key: {{ .Values.realmConfigMap.key }}
            path: sgi-realm.json
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
